spring.config.import=optional:file:.env[.properties]
spring.application.name=productos_crud
spring.datasource.url=${MI_BASE_DE_DATOS_URL}
spring.datasource.username=${MI_BASE_DE_DATOS_USER}
spring.datasource.password=${MI_BASE_DE_DATOS_PASS}
spring.jpa.hibernate.ddl-auto=update
